### ISSUE TITLE
Possible new detector: String.format inside SLF4J logging statement

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#134]
Similarly to LO_APPENDED_STRING_IN_FORMAT_STRING, it may be worth detecting the case when an SLF4J format string is assembled on the fly using `String.format`. Eg:

    LOG.info(String.format("Processing order [%s]", orderId));

This can occur, for example, as a legacy of migrating a codebase from the Log4J API to SLF4J.

**Comment by mebigfatguy** [comment]
you'd have to differentiate special formatting cases like %4d, etc

**Comment by mebigfatguy** [comment]
thanks! seems to be working, but give it a spin if you can.

**Comment by ThrawnCA** [comment]
Looks good :)

**Comment by zolyfarkas** [comment]
Only as FYI, this rule does not work in my apps...
In my apps I have special formatters that will log any unmatched (in format string) arg object.

A log statement like:

LOG.info("Input", Pair.of("argument", someObject))

would result in a log:

..."msg" : "Input", "argument" : { ... myProp ... } ... 

which is why I had to write: https://github.com/zolyfarkas/spf4j/blob/master/spf4j-core/src/main/java/org/spf4j/base/Slf4jMessageFormatter.java 

Our logs are in json format, and we "miss-use" the slf4j api to log structured data... which ends up centralized, indexed, ...

**Comment by ThrawnCA** [comment]
Um...I don't see how a check for `String.format` would interfere with your use case?
