### ISSUE TITLE
false positive PCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOP when adding to list in a loop.

### ISSUE THREAD

**Issue by igorch123** [mebigfatguy/fb-contrib#171]
version 6.6.1 (sonar-findbugs-3.4.3)

constantly reporting PCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOP for the code like below.

```
List<Foo> fooList = new ArrayList<Foo>();
Foo foo;
for (Bar bar : barList ) {
     foo = new Foo();
     foo.setAny(bar.getAny());
     fooList.add(foo);
} 

```

**Comment by mebigfatguy** [comment]
thanks, i copied this code block into a method and ran findbugs on it, but got no such report. Do you have a class that shows this problem?

**Comment by igorch123** [comment]
We use SonarQube with Findbugs. Pease find snippet below.
http://pasteboard.co/EKrBFhzT.jpg

**Comment by mebigfatguy** [comment]
thanks, i appreciate it. I assume this is proprietary code, and i appreciate your attempts to help.

 i tried to replicate as close as possible what you have and am still having trouble reproducing.

I was hoping it was because the add() came at the end of a method chain, but even that didn't seem to cause any problems. (when the code see the object passed as a parameter to a method, it should disqualify it.)

Can you tell me what the attributes are on the add method itself? is it an interface method, or static, or something else non-expected?

If i had to guess i think it's probably some problem with fb-contrib's reliance on findbugs code proper.

If i made a commit, to guess at the problem, could you pull/build a version and check? would that be possible?
