### ISSUE TITLE
Possible issue with SJVU_SUSPICIOUS_JDK_VERSION_USE on Windows

### ISSUE THREAD

**Issue by joankaradimov** [mebigfatguy/fb-contrib#182]
I get: `SJVU_SUSPICIOUS_JDK_VERSION_USE: Method uses rt.jar class or method that does not exist`.

The error details are something similar to:
```
Bug type SJVU_SUSPICIOUS_JDK_VERSION_USE (click for details) 
In class SomeClass
In method SomeClass.someMethod()
At SomeClass.java:[line 327]
In class javax.mail.internet.MimeMessage
```

I get multiple errors like this one. All of them are in the packages "javax.mail" and "javax.crypto". The thing is - neither of those classes are in `rt.jar`. They are in separate jars. And "javax.mail" is not even a part of the JDK.

What's even weirder is that I'm getting these errors on Windows and a coworker of mine who's on Linux does not see them.

**Comment by mebigfatguy** [comment]
Thanks for the report. To be honest i haven't touched this detector in a really long time. I have added code in trunk to attempt to fix your issues, but i still have to do a bunch of testing. there might still be problems here. but a start.

**Comment by joankaradimov** [comment]
Thanks! I'll be waiting for the next release...

**Comment by ThrawnCA** [comment]
The new `SJVU_Sample` broke the Maven build, because `javax.persistence.Cache` wasn't found on the classpath. From what I can see in `samples.xml`, it looks like the Ant build is using `javax.persistence-2.1.1.jar`, whereas the POM declares `persistence-api` version 1.0.2 - although I can't find a `version.properties` anywhere, so I'm not sure how that's being configured in `build.xml`.
