### ISSUE TITLE
Weird message for error

### ISSUE THREAD

**Issue by martofeld** [mebigfatguy/fb-contrib#185]
The following snippet throws OCP_OVERLY_CONCRETE_PARAMETER with the message `1st parameter 'content' could be declared as android.view.KeyEvent$Callback instead` cc @jsotuyod 

![image](https://cloud.githubusercontent.com/assets/5756343/23562578/c8bf4262-0021-11e7-9809-0c66e6573478.png)

**Comment by mebigfatguy** [comment]
i take it you are suggesting i should use the lowest class in the hierarchy that implements anything specified by instanceof, but excluded by !instanceof?

**Comment by jsotuyod** [comment]
I believe the issue here is actually the message... `android.view.KeyEvent$Callback` is a completely unrelated type to `View` and in particular all 3 interesting types being considered by the code ([`ScrollView`](https://developer.android.com/reference/android/widget/ScrollView.html), [`ScrollingView`](https://developer.android.com/reference/android/support/v4/view/ScrollingView.html) and [`AbsListView`](https://developer.android.com/reference/android/widget/AbsListView.html)). I've no idea where fb-contrib is picking that type from....

Possibly the one causing this flag is `ScrollingView`, since that is a marker interface, and therefore not necessarily a `View` (even if in practice only `View`s are marked with it). However, even if fb-contrib decided to flag such snippet, I would have expected it to simply ask for `Object` as the nearest ancestor to an interface and 2 speciallized types of `View`.

**Comment by mebigfatguy** [comment]
i see. any change 'this' is a Callback object? (just trying to figure where it dug that up from).

**Comment by mebigfatguy** [comment]
ah ok, i see View implements KeyEvent.Callback

**Comment by mebigfatguy** [comment]
probably if an object implements more than one interface and they all could apply, you shouldn't suggest any of them. I'll try that.

**Comment by mebigfatguy** [comment]
should be fixed. thanks for the report

**Comment by martofeld** [comment]
Great thanks
