### ISSUE TITLE
Issue in SPP_NO_CHAR_SB_CTOR

### ISSUE THREAD

**Issue by joankaradimov** [mebigfatguy/fb-contrib#199]
I have some code that looks something like (the boilerplate in the `for` is irrelevant):

```java
	private static final int SIZE = 24;
	private static final int DOUBLE_THE_SIZE = SIZE * 2;

	private static String encodeToHexadecimal(byte[] filename) {
		StringBuilder builder = new StringBuilder(DOUBLE_THE_SIZE);
		for (byte b : filename) {
			int byteAsInt = Byte.toUnsignedInt(b);
			builder.append(HEX_DIGITS[byteAsInt / 16]).append(HEX_DIGITS[byteAsInt % 16]);
		}
		return builder.toString();
	}
```

In that case `SPP_NO_CHAR_SB_CTOR` is reported.

What is interesting is that constructing the StringBuilder like so: `new StringBuilder(SIZE)` does not result in a warning. However inlining the constant like this: `new StringBuilder(SIZE * 2)` does yield the warning.

P.S.
fb-contrib version is the latest - 7.0.1

**Comment by mebigfatguy** [comment]
Thanks for the report. Yeah unfortunately this is a tough one to fix. The problem is that javac does funny things with java final ints and longs, in that it doesn't really treat them as fields, it just uses them like constants. So even though it's an int, it uses BIPUSH to load the value, which would be the same thing as if it were a character. The reason why 24 isn't reported is 24 isn't really a used character it's the CANcel code, where as 48 is '0'. 

So i have fixed your exact problem, because 48 is actually a pretty common false positive i've seen before, while this doesn't really fix the problem in general, it helps. as you are unlikely to do new StringBuilder(31); for instance.

the Dead Local Variable detector has a problem for the same reason. (javac's use of static final ints).

**Comment by joankaradimov** [comment]
> Yeah unfortunately this is a tough one to fix

That sounds horrible :)

Definitely not like something that can be done with byte code analysis alone. It's beyond me why Sun decided to make the char->int cast implicit.

Thanks for the quick reaction and the [cheesy] fix!
