### ISSUE TITLE
STT_TOSTRING_MAP_KEYING False Positive

### ISSUE THREAD

**Issue by hazendaz** [mebigfatguy/fb-contrib#222]
Current build on maven results on this when tests run.  I have tried to change underlying code to use stringbuilder.ToString().  The prior logic did use concatination.  I believe this is a false positive given change to string builder and explicit toString.  What exactly is going on here?  Concatination is bad for a lot of reasons but using stringBuilder, I'm not certain why its still an issue.

[INFO] This method com.mebigfatguy.fbcontrib.detect.NonRecycleableTaglibs.getAttributes(JavaClass) uses a concatenated String as a map key [com.mebigfatguy.fbcontrib.detect.NonRecycleableTaglibs] At NonRecycleableTaglibs.java:[line 129] STT_TOSTRING_MAP_KEYING
[INFO] This method com.mebigfatguy.fbcontrib.detect.NonRecycleableTaglibs.sawOpcode(int) uses a concatenated String as a map key [com.mebigfatguy.fbcontrib.detect.NonRecycleableTaglibs] At NonRecycleableTaglibs.java:[line 172] STT_TOSTRING_MAP_KEYING
[INFO]

To see bug detail using the Findbugs GUI, use the following command "mvn findbugs:gui"

**Comment by mebigfatguy** [comment]
Yes, thanks i saw that too, been meaning to fix that...

**Comment by mebigfatguy** [comment]
BTW, the reason for the detector is that 'String' is pretty much completely devoid of meaning. You look at that map key and see 'String' ? what information is that really holding? you have no idea. Also, how easy is it to screw up the 'magic' format of  method + ":" + name...   or was it method + "-" +name, or perhaps just method + name.. That's just awful. Use a real bean so that proper typing is available for the reader to understand what that key really is for.

**Comment by hazendaz** [comment]
Great Point!  Thanks.
