### ISSUE TITLE
PSC_SUBOPTIMAL_COLLECTION_SIZING not correct in 7.2.1?

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#263]
Method new org.spf4j.base.asm.MethodInvocationClassVisitor(Collection, Set) uses suboptimal sizing to allocation a collection [org.spf4j.base.asm.MethodInvocationClassVisitor] At MethodInvocationClassVisitor.java:[line 70] PSC_SUBOPTIMAL_COLLECTION_SIZING

the code in question is:

this.methodStrings = new HashMap<>(methods.size());

for more detail:

https://github.com/zolyfarkas/spf4j/blob/3e330cc5c8397cff57aaa73f6381bc73ad6ffef4/spf4j-asm/src/main/java/org/spf4j/base/asm/MethodInvocationClassVisitor.java#L70

**Comment by mebigfatguy** [comment]
OK, i'm not sure what your issue is, perhaps i'm being dense. The bug fires because it notices that you have guava on the classpath, and that you used the built in new HashMap(int size) constructor which is suboptimal, over Maps.newHashMapWithExpectedSize, because new HashMap doesn't take into account the loading factor. Did i miss something?

**Comment by zolyfarkas** [comment]
Nope, your right... feel free to close...

**Comment by mebigfatguy** [comment]
do you think there needs to be better documentation in the bug pattern info? any suggestions?

**Comment by zolyfarkas** [comment]
The documentation looks good, (I wish I have read it before submitting this issue :-) )
