### ISSUE TITLE
Make it easier for someone to recognise which findbugs rule they must suppress

### ISSUE THREAD

**Issue by athkalia** [mebigfatguy/fb-contrib#60]
Hello,

It seems that the comments in the error itself don't match (down to the word) the descriptions in your web page, making it difficult to track down the error when one needs to suppress it. While you are at it, can't you just add the specific BugType enum (https://github.com/mebigfatguy/fb-contrib/blob/master/src/com/mebigfatguy/fbcontrib/utils/BugType.java) in the error so that one does not have to spend time to find out which one it is in order to suppress it ? 
PMD for example already does this.

Cheers,
Sakis

**Comment by mebigfatguy** [comment]
In the findbugs swing gui at least, it shows the BugType as: 

Bug kind and pattern: ISB - ISB_INEFFICIENT_STRING_BUFFERING


So adding it myself, would stutter there. Your suggestion is good, but perhaps this should be done by Findbugs itself in the other report types. Where are you using findbugs, in Eclipse? or the command line reporter? or ... ?

**Comment by jsotuyod** [comment]
The type is reported as part de XML / HTML report generated by findbugs, for instance:

```
<BugInstance type="SMII_STATIC_METHOD_INSTANCE_INVOCATION" priority="2" rank="17" abbrev="SMII" category="STYLE" instanceHash="dfc815a215952082da2307aac913c196" instanceOccurrenceNum="0" instanceOccurrenceMax="0">
  <ShortMessage>Method calls static method on instance reference</ShortMessage>
  ...
```

The messages (short and long) are just human-readable and reported separately, and mostly intended at understanding the issue at hand (causes, consequences, plausible fixes).
 
This same "issue" applies to findbugs itself (you can see an example message from Findbugs core [here](https://github.com/findbugsproject/findbugs/blob/master/findbugs/etc/messages.xml#L8509)), since that's Findbugs report format. It seems most likely your real issue is with whatever tool you are using to deal with findbugs (be it an eclipse plugin / maven plugin / whatever) not showing relevant data from the XML.

As Dave suggests, any change would probably better be part of either the tool you are using to run findbugs; or at least Findbugs itself.

**Comment by athkalia** [comment]
You are write, sorry. It's the findbugs maven plugin. I'll annoy them instead.

Thanks for the prompt reply.
