### ISSUE TITLE
Alternative to temporary trim (SPP_TEMPORARY_TRIM) for finding Selenium WebElement?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#67]
Our code searches through Selenium web elements to find and select a drop-down option matching a given text, like so:

    public static void select(WebElement element, String text) {
        for (WebElement subElement : element.findElements(By.xpath("option"))) {
            if (subElement.getText().trim().equals(text)) {
                subElement.click();
                return;
            }
        }

        throw new NoSuchElementException("No option with text: " + text + " under " + element);
    }

This triggers SPP_TEMPORARY_TRIM, because it is trimming the element text for the comparison. However, contrary to what the detector suggests, we have no interest in storing the trimmed value for later; we only want to identify the element so we can click on it. Is there a better way to perform this search?

**Comment by mebigfatguy** [comment]
Yeah, that's an unfortunate false positive. 

So lets see. Why is that a valid case. Well it's because you are not using the result of getText() again. So I guess really we should look to see if the thing that is being trimmed, and thrown away, is being used again.

What this would mean is that the trim() call is probably in a conditional expression, and doesn't show up again in the if or else of the conditional.

Ok, that seems right. Let's see what can be done.

**Comment by mebigfatguy** [comment]
The issue is of course the trim() may be called on a string that is produced thru a long chain of methods, (yours is a chain, albeit not to long). Finding that pattern again is probably hard, which is probably why the FP exists today. Maybe it's good enough to look for the last method that produces the string to be trimmed, in this case, look for a call to WebElement.getText() regardless of what web element it was called on. sure that is broken too, but probably reduces the false positives to close to 0.

**Comment by ThrawnCA** [comment]
Well, in this case, there's just a void method call and then return; is that a useful pattern for distinguishing false positives?

Maybe, if there is no further string access (no access to string variables, no method calls returning string) in one branch of the conditional, then it's considered legitimate?

**Comment by mebigfatguy** [comment]
yes that would be good enough to rule out, although, there would still be possible FPs. But that would be better.

**Comment by mebigfatguy** [comment]
@ThrawnCA could you see if that resolves your issue?

**Comment by ThrawnCA** [comment]
Well, it broke the FindBugs check, which is only enforced in the Maven build :D. But it was a deliberate thing (switch fall-through), so I just added a suppression annotation. The trim false positive is fixed :).
