### ISSUE TITLE
SPP_TEMPORARY_TRIM does not like my pattern

### ISSUE THREAD

**Issue by ksobolew** [mebigfatguy/fb-contrib#81]
So, Some Other Developer wrote some code that tripped SPP_TEMPORARY_TRIM, and rightfully so:

        if (searchCrit.getName() != null && !searchCrit.getName().trim().equals("")) {
            sqlQuery.setString("account_name", searchCrit.getName() + "%");

So I changed it to:

        String name = searchCrit.getName();
        if (name != null && !(name = name.trim()).equals("")) {
            sqlQuery.setString("account_name", name + "%");

(mostly because I don't like small changes like this ballooning the diff because I changed indentation on a huge block after the && condition was split in order to make room for a temporary variable.) And it worked fine for some time, until I upgraded fb-contrib to 6.4.0, after which this pattern trips SPP_TEMPORARY_TRIM again. BTW: it also trips if I introduce another variable instead of reassigning `name`.

Thanks :)

**Comment by mebigfatguy** [comment]
ok. 6.4 changed to try to remove more false positives here, but i guess i foobared that. Will look at it. thanks for the report.

**Comment by mebigfatguy** [comment]
Looks like the issue is due to a DUP before an ASTORE

5: invokevirtual #388                // Method java/lang/String.trim:()Ljava/lang/String;
         8: dup
         9: astore_2

that reg on the stack remains with a flag that says it was trimmed. So the fix is, when i do an ASTORE with a trimmed string, look to see if the previous OP was a DUP, and if so clear that stackop's flag as well.
