### ISSUE TITLE
What is the point of STT_STRING_PARSING_A_FIELD?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#90]
There are a few instances of STT_STRING_PARSING_A_FIELD in the fb-contrib codebase, which are proving difficult to eliminate to the detector's satisfaction (eg ``PoorlyDefinedParameter`` line 120), but I can't see the actual problem with this pattern. Why is there a detector for it?

**Comment by mebigfatguy** [comment]
the goal of the detector is to encourage people to use classes to hold composite data, not strings. So when a field of a class is a String and then code in that class picks apart pieces of that String what you are doing is subdividing 'faux fields' of the String, instead of real fields of some object.

**Comment by ThrawnCA** [comment]
Ok...so, should fb-contrib include a class that parses a classname and encapsulates its components?

**Comment by mebigfatguy** [comment]
that one should be fixed now
